/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SimpleToDoInterface extends utils.Interface {
  functions: {
    "addTask()": FunctionFragment;
    "owner()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "addTask" | "owner"): FunctionFragment;

  encodeFunctionData(functionFragment: "addTask", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;

  events: {
    "CreatedTask(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatedTask"): EventFragment;
}

export interface CreatedTaskEventObject {
  sender: string;
  task: BigNumber;
}
export type CreatedTaskEvent = TypedEvent<
  [string, BigNumber],
  CreatedTaskEventObject
>;

export type CreatedTaskEventFilter = TypedEventFilter<CreatedTaskEvent>;

export interface SimpleToDo extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SimpleToDoInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addTask(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;
  };

  addTask(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addTask(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CreatedTask(address,uint256)"(
      sender?: PromiseOrValue<string> | null,
      task?: PromiseOrValue<BigNumberish> | null
    ): CreatedTaskEventFilter;
    CreatedTask(
      sender?: PromiseOrValue<string> | null,
      task?: PromiseOrValue<BigNumberish> | null
    ): CreatedTaskEventFilter;
  };

  estimateGas: {
    addTask(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addTask(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
