/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155DeltaQueryable } from "./ERC1155DeltaQueryable";
export type { ERC1155DeltaQueryableUpgradeable } from "./ERC1155DeltaQueryableUpgradeable";
export type { IERC1155DeltaQueryable } from "./IERC1155DeltaQueryable";
