/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { ERC1155Delta__factory } from "./ERC1155Delta__factory";
export { ERC1155DeltaUpgradeable__factory } from "./ERC1155DeltaUpgradeable__factory";
export { IERC1155Delta__factory } from "./IERC1155Delta__factory";
