/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { ERC1155Delta } from "./ERC1155Delta";
export type { ERC1155DeltaUpgradeable } from "./ERC1155DeltaUpgradeable";
export type { IERC1155Delta } from "./IERC1155Delta";
